### ISSUE TITLE
Coptic data

### ISSUE THREAD

**Issue by amir-zeldes** [juand-r/entity-recognition-datasets#12]
I'm not sure if you'd be interested in this, but we have about 46,000 tokens of nested (non-)named and Wikified entities in Coptic, here: https://github.com/UniversalDependencies/UD_Coptic-Scriptorium/tree/dev

If it's not relevant, feel free to just close the issue.

**Comment by juand-r** [comment]
Definitely relevant. Thanks for the suggestion!  I added a link to this right before Amharic.
