### ISSUE TITLE
Information of the datasets

### ISSUE THREAD

**Issue by CamilleSchr** [juand-r/entity-recognition-datasets#15]
Hello,

Thanks for sharing these datasets !
I just try to find some more specific information on it ; for instance, how many tweets/comments/news are on the WNUT17 and on the CONLL 2003 ?

Thanks,
Cheers,
Camille

**Comment by juand-r** [comment]
Hi Camille,

It's probably best to find these statistics in either the associated papers or by looking at the datasets. However, I do have some statistics (number of tokens, sentences, and annotated entities by entity type) for these two:

https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/docs/entity-list.txt
https://github.com/juand-r/entity-recognition-datasets/blob/master/data/conll2003/CONLL-format/docs/entity-list.txt
