### ISSUE TITLE
Worldwide English NER Dataset -- EMNLP 2023

### ISSUE THREAD

**Issue by SecroLoL** [juand-r/entity-recognition-datasets#26]
https://arxiv.org/abs/2404.13465

This paper introduces the Worldwide NER dataset for English which includes multiple English contexts from every continent of the world. 

Dataset can be found here: https://github.com/stanfordnlp/en-worldwide-newswire

The dataset can be processed using the StanfordNLP Stanza library

**Comment by AngledLuffa** [comment]
how embarrassing of me!

https://github.com/juand-r/entity-recognition-datasets/commit/f37ee10aa262bb91cb907d4c6b479d07f1345044
