### ISSUE TITLE
Any dataset for Legal category? 

### ISSUE THREAD

**Issue by sunn-e** [juand-r/entity-recognition-datasets#4]
I couldn't find any dataset relalated to legal domain.

**Comment by juand-r** [comment]
I don't know of any in English.  If you happen to find one please let me know and I can add it. There are a few in some other languages:

- Portuguese: LeNER-Br (Brazilian legal documents): https://cic.unb.br/~teodecampos/LeNER-Br/
- Greek: PANACEA Annotated Greek Labour Legislation Corpus:  http://panacea-lr.eu/en/info-for-researchers/data-sets/dependency-parsed-corpora/dependency-lab-el
- German: https://github.com/elenanereiss/Legal-Entity-Recognition ; described in this paper: http://georg-re.hm/pdf/LREC-2020-Leitner-et-al-preprint.pdf
