### ISSUE TITLE
New Romainian Named Entity Corpus (RONEC)

### ISSUE THREAD

**Issue by avramandrei** [juand-r/entity-recognition-datasets#6]
Hello,

Me and my colleague created a new named entity corpus for the Romanian language - RONEC. The paper (recently accepted at LREC2020) can be found at https://arxiv.org/abs/1909.01247 and the repository at https://github.com/dumitrescustefan/ronec. 

Could you add our corpus along the others at the Romanian language?

Thank you,
Avram Andrei-Marius

**Comment by juand-r** [comment]
I just added it.  Thanks for the recommendation!
